config/routes.rb
Rails.application.routes.draw do
	get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
	get '/logout' => 'sessions#destroy'

	get '/' => 'apps#index'
	resources :settlements, only: [:index]
	resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/settlement.rb
class Settlement < ApplicationRecord
	# validates :name, presence: true
	# belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :password, length: { minimum: 3, too_short: ' has to be more than %{count} ' }
	validates :email, :username, presence: true, uniqueness: true
	validates :password, presence: true

	has_many :settlements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
	def index
		@settlements = Settlement.all
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	include SessionsHelper

	def new
		@user = User.new
	end

	def create
		@user = User.find_by(email: params[:email])
		if @user && @user.authenticate(params[:password])
			login(@user)
			redirect_to @user
		else
			@error = "login failed !"
			render :new
		end
	end

	def destroy
		logout
		redirect_to '/'
	end
end

app/controllers/settlements_controller.rb
class SettlementsController < ApplicationController
	
	def index
		@settlements = Settlement.order(name: :asc)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper
	
	def new
		@user = User.new()
	end

	def create
		@user = User.new(user_params)
		if @user.save
			login(@user)
			redirect_to '/'
		else
			@errors = @user.errors.full_messages
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
	end

	private 

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def login(user)
		session[:user_id] = user.id
	end

	def logout
		session.clear
	end

	# def current_user
	# 	User.find(session[:user_id]) if session[:user_id]
	# end

	# or 
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

end

app/views/apps/index.html.erb
<h2> home </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fallout 4 Progress Tracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
<!-- menubar -->

	<div id="menubar">
    <ul class="menubar">
      <li> <%= link_to 'home', '/', class: 'left-links' %> </li>
      <li> <%= link_to 'settlements', settlements_path, class: 'left-links' %> </li>
      <li> <%= link_to 'items', '#', class: 'left-links' %> </li>
    <% if current_user %>
      <li> <%= link_to 'logout', '/logout', class: 'right-links' %> </li>
      <% else %>
      <li> <%= link_to 'sign up', new_user_path, class: 'right-links' %> </li>
      <li> <%= link_to 'login', login_path, class: 'right-links' %> </li>
    <% end %>

    </ul> <!-- ul menubar  -->
  </div>  <!-- div menubar -->


  <body id="main-body">
    <%= yield %>
  </body>
</html>

app/views/settlements/index.html.erb
<h1> all settlements </h1>

<% @settlements.each do |s| %>
	<%= s.name %>
<% end %>

app/views/users/_user_form.erb
<%= form_for @user do |f| %>
	<%= f.label :username %>
	<%= f.text_field :username %>

	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h2> user sign up </h2>

<%= render 'user_form' %>

<% if @errors %>
	<% @errors.each do |e| %>
		<li> <%= e %> </li>
	<% end %>
<% end %>

<%= link_to 'already signed up ? click here', '/login' %>

app/views/users/show.html.erb
<h2> user profile </h2>

<h3> username : <%= @user.username %> </h3>
<h3> email : <%= @user.email %> </h3>